spring:
  datasource:
    url: jdbc:mysql://116.62.108.118:3306/monitoringsystem
    username: root
    password: Hxy_116991
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
server:
  port: 8183
